- name: pre
  gather_facts: No
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Install required
      yum:
        name: python3-setuptools, virtualenv, python3-pip, curl, ca-certificates
        state: latest

    - name: Install py
      pip:
        name: docker-py
        state: latest
